# Site settings
baseurl = "https://smerrell.github.io/"
languageCode = "en-us"
title = "Sam Merrell"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = ""

pygmentsCodeFences = true
pygmentsOptions = "linenos=inline"
pygmentsUseClasses = true

[permalinks]
  post = "/:year/:month/:title/"

[params]
	name = "Sam Merrell"
	description = "Personal Blog"
	bio = "Learning & Dabbling"
	# Enter optionally your twitter account
	twitter = "smerrell"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I like to learn new things."
	tweet = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "rounded"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/smerrell"
    github   = "https://www.github.com/smerrell"
